[package]
name        = "basis-base"
description = "Flix wrappers over the JDK libraries built on top of interop-base."
version     = "0.4.2"
flix        = "0.39.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

[dependencies]
"github:stephentetley/graded-lib"                = "0.7.0"
"github:stephentetley/interop-base"              = "0.7.0"
